### ISSUE TITLE
Python 3 incompattability

### ISSUE THREAD

**Issue by Richard-Mathie** [amey-sam/Flask-MailGun#15]
It seems like there are issues around saving attachments in python3 need to investigate
```
======================================================================
ERROR: test_receive_message (tests.test_receve.ReceiveMessageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/amey-sam/Flask-MailGun/tests/test_receve.py", line 32, in test_receive_message
    response = self.appclient.post('/upload', data=request)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/werkzeug/test.py", line 801, in post
    return self.open(*args, **kw)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/flask/testing.py", line 127, in open
    follow_redirects=follow_redirects)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/werkzeug/test.py", line 754, in open
    environ = args[0].get_environ()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/werkzeug/test.py", line 552, in get_environ
    stream_encode_multipart(values, charset=self.charset)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/werkzeug/test.py", line 98, in stream_encode_multipart
    write_binary(chunk)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/werkzeug/test.py", line 59, in write_binary
    stream.write(string)
TypeError: a bytes-like object is required, not 'str'
======================================================================
ERROR: test_save_attachments (tests.test_save_attachments.SaveAttachmentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/amey-sam/Flask-MailGun/tests/test_save_attachments.py", line 35, in test_save_attachments
    filenames = save_attachments([self.attachment], testdir)
  File "/home/travis/build/amey-sam/Flask-MailGun/flask_mailgun/attachment.py", line 52, in save_attachments
    attachment.save(filename)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/werkzeug/datastructures.py", line 2706, in save
    copyfileobj(self.stream, dst, buffer_size)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/shutil.py", line 76, in copyfileobj
    fdst.write(buf)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by aerickson** [comment]
I think this broke attachment sending. I'm able to send when running dd15a0abcc28bed19cc4c96c02ce80bf58871525, but not head.

Strangely it gives the same error that was fixed.

```
(my code above this point in the stack)
...
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/src/flask-mailgun3/flask_mailgun/core.py", line 51, in send
08:45:44 web.1  |     return self.mailgun_api.send(message)
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/src/flask-mailgun3/flask_mailgun/api.py", line 80, in send
08:45:44 web.1  |     files=files)
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/requests/api.py", line 112, in post
08:45:44 web.1  |     return request('post', url, data=data, json=json, **kwargs)
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/requests/api.py", line 58, in request
08:45:44 web.1  |     return session.request(method=method, url=url, **kwargs)
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
08:45:44 web.1  |     prep = self.prepare_request(req)
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
08:45:44 web.1  |     hooks=merge_hooks(request.hooks, self.hooks),
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/requests/models.py", line 308, in prepare
08:45:44 web.1  |     self.prepare_body(data, files, json)
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/requests/models.py", line 496, in prepare_body
08:45:44 web.1  |     (body, content_type) = self._encode_files(files, data)
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/requests/models.py", line 162, in _encode_files
08:45:44 web.1  |     rf.make_multipart(content_type=ft)
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/urllib3/fields.py", line 174, in make_multipart
08:45:44 web.1  |     (('name', self._name), ('filename', self._filename))
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/urllib3/fields.py", line 134, in _render_parts
08:45:44 web.1  |     parts.append(self._render_part(name, value))
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/urllib3/fields.py", line 114, in _render_part
08:45:44 web.1  |     return format_header_param(name, value)
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/urllib3/fields.py", line 35, in format_header_param
08:45:44 web.1  |     if not any(ch in value for ch in '"\\\r\n'):
08:45:44 web.1  |   File "/Users/aje/git/inqqqq/venv/lib/python3.6/site-packages/urllib3/fields.py", line 35, in <genexpr>
08:45:44 web.1  |     if not any(ch in value for ch in '"\\\r\n'):
08:45:44 web.1  | TypeError: a bytes-like object is required, not 'str'
```
